### ISSUE TITLE
Whould you mind adding Python 3.7 please?

### ISSUE THREAD

**Issue by webknjaz** [randomknowledge/docker-pyenv-tox#1]

**Comment by randomknowledge** [comment]
Added 3.7.0
Dockerhub is building it now: https://hub.docker.com/r/randomknowledge/docker-pyenv-tox/builds/

**Comment by webknjaz** [comment]
Thank you!

**Comment by webknjaz** [comment]
Oh, by the way, README says it's for GitLab, but I'm running it in Circle CI. JFYI, you might want to extend it :)

**Comment by randomknowledge** [comment]
I started this as my personal Gitlab (CI) image and didn't expect somebody else using it ;-)
I'll extend the README when I find the time, but feel free to do a pull request.

**Comment by webknjaz** [comment]
Yeah, I think I've found it in some discussion on GitLab and decided to follow principle of not reinventing the wheel :)

**Comment by randomknowledge** [comment]
Sure, I am glad someone uses this!
